app:
    cors:
        allowed-origins:
            - "http://localhost:5173"
        allowed-methods:
            - "GET"
            - "POST"
            - "PUT"
            - "PATCH"
            - "DELETE"
            - "OPTIONS"
        allowed-headers:
            - "Authorization"
            - "Content-Type"
        allow-credentials: false
             
spring:
    application:
        name: blueArchiveMusicApi
    profiles:
        # If SPRING_PROFILES_ACTIVE exists, use it.
        # Otherwise, default to dev.
        active: ${SPRING_PROFILES_ACTIVE:dev}
    docker:
        compose:
            enabled: false
    cache:
        type: redis
    data:
        redis:
            url: ${blueArchive.redis.url}
    datasource:
        url: ${blueArchive.datasource.url}
        username: ${blueArchive.datasource.username}
        password: ${blueArchive.datasource.password}
    servlet:
        multipart:
            enabled: true
            max-file-size: 50MB
            max-request-size: 70MB
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                jdbc:
                    batch_size: 100
                order_updates: true
    flyway:
        baseline-on-migrate: true
        validate-on-migrate: true

cloudflare:
    r2:
        endpoint:  ${blueArchive.r2.endpoint}
        accessKey: ${blueArchive.r2.accessKey}
        secretKey: ${blueArchive.r2.secretKey}
        bucket: ${blueArchive.r2.bucket}


