CREATE TABLE artist (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE song
ADD COLUMN artist_id INTEGER,
ADD COLUMN composer_id INTEGER;

ALTER TABLE song
ADD CONSTRAINT fk_song_artist
    FOREIGN KEY (artist_id) REFERENCES artist(id) ON DELETE SET NULL,
ADD CONSTRAINT fk_song_composer
    FOREIGN KEY (composer_id) REFERENCES artist(id) ON DELETE SET NULL;

ALTER TABLE song
DROP COLUMN artist,
DROP COLUMN composer;

